### ISSUE TITLE
irisFetch.Resp method needs more documentation

### ISSUE THREAD

**Issue by chad-iris** [iris-edu/irisFetch-matlab#1]
The current, incode help for the irisFetch.Resp method is pretty thin.  In particular it does not include the calling convention (it is displayed in the GUI popup for the method, but we shouldn't rely on solely).

Adding an example would be good too, e.g.:
`resp = irisFetch.Resp('IU','COLA','00','LHZ','2000-01-01 00:00:00','2020-01-01 00:00:00');`

Current help:
```
>> help irisFetch.Resp
  retrieve the Resp information into a character string.
  net, sta, loc, and cha are all required.
  channels and locations may be wildcarded using either ? or *
  starttime and endtime options may be ignored by using [] instead of a time.
```

**Comment by rtweekly-iris** [comment]
Added parameter list, output description, and example.
