### ISSUE TITLE
irisFetch.Traces() returns 204 error when requesting data that should be available.

### ISSUE THREAD

**Issue by b-jancovich** [iris-edu/irisFetch-matlab#18]
I am getting errors when making irisFetch.Traces() requests, using version '2.0.12', cloned from Git. 
My startDate and endDate values are set programmatically, and are generated with type "datetime".
I am making the request as follows:

`data = irisFetch.Traces('IM', 'H01W1', '--', 'EDH', chunk_start, chunk_end);`

Here, "chunk_start" and "chunk_end" are 1x1 "datetime" arrays. This results in the following error:

`edu.iris.dmc.service.NoDataFoundException: (204) No data found for: quality=M
IM H01W1 -- EDH 2010-01-01T00:00:00.000 2010-01-02T00:00:00.000
	at edu.iris.dmc.service.WaveformService.fetch(WaveformService.java:116)
	at edu.iris.dmc.service.WaveformService.fetch(WaveformService.java:239)
	at edu.iris.dmc.service.WaveformService.fetch(WaveformService.java:292)
	at edu.iris.dmc.extensions.fetch.TraceData.fetchTraces(TraceData.java:394)
	at edu.iris.dmc.extensions.fetch.TraceData.fetchTraces(TraceData.java:192)
	at edu.iris.dmc.extensions.fetch.TraceData.fetchTraces(TraceData.java:137)
	at edu.iris.dmc.extensions.fetch.TraceData.fetchTraces(TraceData.java:102)`
 
According to [this page](https://ds.iris.edu/mda/IM/H01W1/--/EDH/?starttime=2001-08-28&endtime=2599-12-31), the data for the dates I am requesting are available.

I have tried specifying other values for "quality" but this does not prevent the error.
I gave tried converting the 'datetime' arrays to strings, resulting in the following request:
`data = irisFetch.Traces('IM', 'H01W1', '--', 'EDH', '2010-01-01 00:00:00', '2010-01-02 00:00:00');`

This results in an identical error.
Any assistance would be most appreciated.

Thanks,
Ben

**Comment by chad-earthscope** [comment]
Hi @b-jancovich 

The data for that channel is not available at our data center for the time range you selected.  You can check for data existence in a number of ways, for example in MDA (https://ds.iris.edu/mda/IM/H01W1/--/EDH/) there is a data availability indicator for the "IRIS DMC" data center (see attached image).

<img width="608" alt="Screenshot 2023-05-08 at 8 30 41 AM" src="https://user-images.githubusercontent.com/16736618/236865602-9a86b4be-8c09-45ba-a249-67357781b8ab.png">

As you can see the earliest data available for that channel is 2014-12-08.

Another way to check for the availability of data is to use a data center's availablity service, for example: https://service.iris.edu/fdsnws/availability/1/extent?format=text&net=IM&sta=H01W1&cha=EDH&orderby=nslc_time_quality_samplerate&includerestricted=false&nodata=404

**Comment by b-jancovich** [comment]
Thanks Chad,
I have already used the MDA to pull what I thought were available data dates, but it seems I misunderstood the “start” and “end” fields for the instrument to be the data availability dates.
Thanks for your help.

Ben

**Comment by b-jancovich** [comment]
Hi Chad,
Returns: Could please answer another question for me?
irisFetch.Traces() is returning multiple traces for a single query, with start & end times that indicate discontinuities or missing data.
Eg:
                chunk = irisFetch.Traces(‘IM’, “H01W1”, ‘—-', ‘EDH’, ‘2015-01-01 00:00:00.000000’, ‘2015-01-02 00:00:00.000000’);

Returns:
Chunk = 1x4 struct with 21 fields:
       network      station      sampleCount  startDate                  endDate
'IM'                        'H01W1'                13182637             '2015-01-01 00:00:00.000'             '2015-01-01 14:38:50.665'
'IM'                        'H01W1'                360000                  '2015-01-01 14:40:40.669'             '2015-01-01 15:04:40.669'
'IM'                        'H01W1'                310000                  '2015-01-01 15:05:50.673'             '2015-01-01 15:26:30.672'
'IM'                        'H01W1'                7679814                '2015-01-01 15:28:00.676'             '2015-01-01 23:59:59.999'

Is this to be expected of IM/CTBTO Hydrophone data?

Many thanks,
Ben

From: Ben Jancovich
Sent: Tuesday, May 9, 2023 7:12 AM
To: iris-edu/irisFetch-matlab ***@***.***>; iris-edu/irisFetch-matlab ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [iris-edu/irisFetch-matlab] irisFetch.Traces() returns 204 error when requesting data that should be available. (Issue #18)

Thanks Chad,
I have already used the MDA to pull what I thought were available data dates, but it seems I misunderstood the “start” and “end” fields for the instrument to be the data availability dates.
Thanks for your help.

Ben
