### ISSUE TITLE
irisFetch doesn't recognize https for specifying a new base url

### ISSUE THREAD

**Issue by dwilson-usgs** [iris-edu/irisFetch-matlab#7]
Specifying a new base url as described here (https://ds.iris.edu/ds/nodes/dmc/software/downloads/irisFetch.m/2-0-10/manual/#retrieving-data-from-global-fdsn-data-centers-and-the-iris-federator) doesn't work if your webservices URL has a https address.  Line 434 should be changed to something like 
if length(param)>7 && (strcmpi(param(1:7),'http://') || strcmpi(param(1:7),'https:/'))
to get it to work.

**Comment by rtweekly-iris** [comment]
Can confirm that specifying a new base URL using https will not work, if only specifying the URL domain. Will include a fix in upcoming patch. That if statement is a little overcomplicated and awkward, will work to make argument validation more straight-forward and robust.

As a potential work-around in the meantime, have you tried explicitly setting the station and dataselect URL targets separately? I have found this to be successful when querying for Raspberry Shake data, for instance. Something like:
`tr =irisFetch.Traces(...,'STATIONURL:https://path/to/stationservice/url','DATASELECTURL:https://path/to/dataselect/url')`

**Comment by dwilson-usgs** [comment]
Thanks, yes it does work if I specify both STATIONURL and DATASELECTURL,
but not if I just specify the DATASELECTURL.

Thanks,
Dave

**Comment by rtweekly-iris** [comment]
Will be adding the capability to specify a single service base using "https://" in the near future.
